# Site settings
title: Applied Systems Lab @ UTD
name: Applied Systems Lab @ UTD
email: jrutsh@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
  Add Description
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://Applied-Systems-Lab.github.io
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# News
# -----------------------------------------------------------------------------
blog_name: Applied Systems Lab @ UTD
blog_description: 

# Pagination
paginate: 4
permalink: pretty

text:
  pagination:
    newer: 'Newer'
    older: 'Older'


# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true


# # -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  members:
    output: true
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /:path/
  # research:
  #   output: true
    # permalink: /:collection/:path/
  # networks:
  #   output: true
  #   permalink: /research/:collection/:path/
  # security:
  #   output: true
  #   permalink: /research/:collection/:path/
  # news:
  #   defaults:
  #     layout: post
  #   output: true
  #   permalink: /updates/:path/
  # projects:
  #   output: true
  #   permalink: /projects/:path/
  # pastsem:
  #   output: true
  #   permalink: /pastsem/:path/

# news_limit: 5


# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
    - jekyll-sitemap


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
